name: Waterloo CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Welcome to CI/CD
        run: echo "Welcome to CI/CD"
